os: osx
language: xamarin
solution: testxplat
osx_image: xcode9.4

mono:
  mdk: 4.6.2
  android: 7.0.2-42
  ios: 10.3.1.8

android:
  components:
    - build-tools-25.0.1
    - android-24
    - extra

install:
  - mono nuget restore testxplat.sln
  #- xbuild /t:SignAndroidPackage /p:Configuration=Release Droid/solution-name.Droid.csproj
  #- xbuild /p:Configuration="Release" /p:Platform="iPhone" /p:IpaPackageDir="$HOME/Builds" /t:Build testxplat.sln

script:
  - xbuild /p:Configuration=Release testxplat.sln
